project:
  type: book
  output-dir: docs

book:
  title: "BAM Manuscript"
  author: "Pictor, L., Laboe, A., Dillon, K., Gavuji, M., Frank, M., & Schaumberg, K."
  date: "6/5/2023"
  chapters:
    - index.qmd
    - Sample_Description.qmd
    - Feasibility.qmd
    - InterventionEffects.KS.qmd
    - tabs/results_tables.RData
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

