# Abstract {.unnumbered}

The Body Advocacy Movement (BAM) is a novel, cognitive-dissonance based intervention designed to target fatphobia and anti-fat bias as mechanisms to drive reductions in eating disorder (ED) risk. Previous dissonance-based programs (i.e., the Body Project; BP) have successfully targeted internalization of appearance ideals as an intervention mechanism. As burgeoning research indicates that fatphobia and anti-fat bias may play a central role in the maintenance of ED pathology, a focused intervention designed to target fatphobia and anti-fat bias could bolster prevention efforts. The aims of this pilot study include confirming acceptability and feasibility of BAM and developing preliminary estimates of its effects on salient intervention targets, along with benchmarking these effects against a similarly-delivered BP intervention. BAM was found to be accepted by participants and feasible to facilitate in a peer-led model. Preliminary results from 50 participants (BAM: N = 26; BP: N = 24) reveal small-to-moderate pre-to- post intervention effects on fatphobia, anti-fat bias, thin ideal internalization, and eating pathology, which dissipated at 8-week follow-up. The BAM intervention has the potential to supplement the existing suite of ED prevention programs by specifically targeting anti- fat bias, though additional efficacy testing in larger and more diverse samples is necessary to clarify its impact on both hypothesized risk mechanisms and ED outcomes.
