---
title: "Intervention Effects"
format: html
editor: visual
---

# Intervention Effects

```{r message=FALSE, echo=FALSE, warning=FALSE}
library(haven)
library(dplyr)
```

```{r message=FALSE, echo=FALSE, warning=FALSE}
### N for participants at each timepoint###
load("Data/BAM_redcap_long_merged.2023-08-11.RData")
fp_base_dataset <- subset(BAM_redcap_long_merged, group == 'FP' & timepoint == 'baseline')
bp_base_dataset <- subset(BAM_redcap_long_merged, group == 'BP' & timepoint == 'baseline')

fp_post_dataset <- subset(BAM_redcap_long_merged, group == 'FP' & timepoint == 'post')
bp_post_dataset <- subset(BAM_redcap_long_merged, group == 'BP' & timepoint == 'post')

fp_8wk_dataset <- subset(BAM_redcap_long_merged, group == 'FP' & timepoint == '8wk')
bp_8wk_dataset <- subset(BAM_redcap_long_merged, group == 'BP' & timepoint == '8wk')

total_baseline_data <- subset(BAM_redcap_long_merged,timepoint == 'baseline')

###Selecting only pps that have completed all 3 timepoints###

completed_participants <- with(BAM_redcap_long_merged, id[ave(timepoint, id, FUN = function(x) length(unique(x))) == 3])

### Split data into BAM and Body Project ###
BAM_dataset <- subset(BAM_redcap_long_merged, id %in% completed_participants & group == 'FP')
Body_Project_dataset <- subset(BAM_redcap_long_merged, id %in% completed_participants & group == 'BP')

###split up the groups by timepoints###
bam_baseline <- subset(BAM_dataset, timepoint == 'baseline')
bam_post <- subset(BAM_dataset, timepoint == 'post')
bam_8week <- subset(BAM_dataset, timepoint == '8wk')

bp_baseline <- subset(Body_Project_dataset, timepoint == 'baseline')
bp_post <- subset(Body_Project_dataset, timepoint == 'post')
bp_8wk <- subset(Body_Project_dataset, timepoint == '8wk')

```

```{r message=FALSE, echo=FALSE, warning=FALSE}
###BAM GFFS analysis###
mean_fp_gffs_base <- round(mean(bam_baseline$gffs_sum_25,na.rm = TRUE), 2)
mean_fp_gffs_post <- round(mean(bam_post$gffs_sum_25,na.rm = TRUE), 2)
mean_fp_gffs_wk8 <- round(mean(bam_8week$gffs_sum_25,na.rm = TRUE), 2)

sd_fp_gffs_base <- round(sd(bam_baseline$gffs_sum_25,na.rm = TRUE), 2)
sd_fp_gffs_post <- round(sd(bam_post$gffs_sum_25,na.rm = TRUE), 2)
sd_fp_gffs_wk8 <- round(sd(bam_8week$gffs_sum_25,na.rm = TRUE), 2)

cd_fp_gffs_base_post <- round((mean_fp_gffs_post - mean_fp_gffs_base) / sqrt((sd_fp_gffs_base^2 + sd_fp_gffs_post^2) / 2), 2)
cd_fp_gffs_base_wk8 <- round((mean_fp_gffs_wk8 - mean_fp_gffs_base) / sqrt((sd_fp_gffs_base^2 + sd_fp_gffs_wk8^2) / 2), 2)
cd_fp_gffs_post_wk8 <- round((mean_fp_gffs_wk8 - mean_fp_gffs_post) / sqrt((sd_fp_gffs_post^2 + sd_fp_gffs_wk8^2) / 2), 2)

###BP GFFS Analysis###
mean_bp_gffs_base <- round(mean(bp_baseline$gffs_sum_25,na.rm = TRUE), 2)
mean_bp_gffs_post <- round(mean(bp_post$gffs_sum_25,na.rm = TRUE), 2)
mean_bp_gffs_wk8 <- round(mean(bp_8wk$gffs_sum_25,na.rm = TRUE), 2)

sd_bp_gffs_base <- round(sd(bp_baseline$gffs_sum_25,na.rm = TRUE), 2)
sd_bp_gffs_post <- round(sd(bp_post$gffs_sum_25,na.rm = TRUE), 2)
sd_bp_gffs_wk8 <- round(sd(bp_8wk$gffs_sum_25,na.rm = TRUE), 2)

cd_bp_gffs_base_post <- round((mean_bp_gffs_post - mean_bp_gffs_base) / sqrt((sd_bp_gffs_base^2 + sd_bp_gffs_post^2) / 2), 2)
cd_bp_gffs_base_wk8 <- round((mean_bp_gffs_wk8 - mean_bp_gffs_base) / sqrt((sd_bp_gffs_base^2 + sd_bp_gffs_wk8^2) / 2), 2)
cd_bp_gffs_post_wk8 <- round((mean_bp_gffs_wk8 - mean_bp_gffs_post) / sqrt((sd_bp_gffs_post^2 + sd_bp_gffs_wk8^2) / 2), 2)
```

```{r message=FALSE, echo=FALSE, warning=FALSE}
bam_baseline$umb_total_sum_25 <- as.numeric(bam_baseline$umb_total_sum_25)

###BAM UMB-FAT analysis###
mean_fp_umbfat_base <- round(mean(bam_baseline$umb_total_sum_25, na.rm = TRUE), 2)
mean_fp_umbfat_post <- round(mean(bam_post$umb_total_sum_25, na.rm = TRUE), 2)
mean_fp_umbfat_wk8 <- round(mean(bam_8week$umb_total_sum_25, na.rm = TRUE), 2)

sd_fp_umbfat_base <- round(sd(bam_baseline$umb_total_sum_25, na.rm = TRUE), 2)
sd_fp_umbfat_post <- round(sd(bam_post$umb_total_sum_25, na.rm = TRUE), 2)
sd_fp_umbfat_wk8 <- round(sd(bam_8week$umb_total_sum_25, na.rm = TRUE), 2)

cd_fp_umbfat_base_post <- round((mean_fp_umbfat_post - mean_fp_umbfat_base) / sqrt((sd_fp_umbfat_base^2 + sd_fp_umbfat_post^2) / 2), 2)
cd_fp_umbfat_base_wk8 <- round((mean_fp_umbfat_wk8 - mean_fp_umbfat_base) / sqrt((sd_fp_umbfat_base^2 + sd_fp_umbfat_wk8^2) / 2), 2)
cd_fp_umbfat_post_wk8 <- round((mean_fp_umbfat_wk8 - mean_fp_umbfat_post) / sqrt((sd_fp_umbfat_post^2 + sd_fp_umbfat_wk8^2) / 2), 2)

###BP UMB-FAT analysis###
mean_bp_umbfat_base <- round(mean(bp_baseline$umb_total_sum_25, na.rm = TRUE), 2)
mean_bp_umbfat_post <- round(mean(bp_post$umb_total_sum_25, na.rm = TRUE), 2)
mean_bp_umbfat_wk8 <- round(mean(bp_8wk$umb_total_sum_25, na.rm = TRUE), 2)

sd_bp_umbfat_base <- round(sd(bp_baseline$umb_total_sum_25, na.rm = TRUE), 2)
sd_bp_umbfat_post <- round(sd(bp_post$umb_total_sum_25, na.rm = TRUE), 2)
sd_bp_umbfat_wk8 <- round(sd(bp_8wk$umb_total_sum_25, na.rm = TRUE), 2)

cd_bp_umbfat_base_post <- round((mean_bp_umbfat_post - mean_bp_umbfat_base) / sqrt((sd_bp_umbfat_base^2 + sd_bp_umbfat_post^2) / 2), 2)
cd_bp_umbfat_base_wk8 <- round((mean_bp_umbfat_wk8 - mean_bp_umbfat_base) / sqrt((sd_bp_umbfat_base^2 + sd_bp_umbfat_wk8^2) / 2), 2)
cd_bp_umbfat_post_wk8 <- round((mean_bp_umbfat_wk8 - mean_bp_umbfat_post) / sqrt((sd_bp_umbfat_post^2 + sd_bp_umbfat_wk8^2) / 2), 2)
```

```{r message=FALSE, echo=FALSE, warning=FALSE}
###BAM EPSI subscale analysis###
mean_fp_epsi_base <- round(mean(bam_baseline$epsi_neg_obese_25, na.rm = TRUE), 2)
mean_fp_epsi_post <- round(mean(bam_post$epsi_neg_obese_25, na.rm = TRUE), 2)
mean_fp_epsi_wk8 <- round(mean(bam_8week$epsi_neg_obese_25, na.rm = TRUE), 2)

sd_fp_epsi_base <- round(sd(bam_baseline$epsi_neg_obese_25, na.rm = TRUE), 2)
sd_fp_epsi_post <- round(sd(bam_post$epsi_neg_obese_25, na.rm = TRUE), 2)
sd_fp_epsi_wk8 <- round(sd(bam_8week$epsi_neg_obese_25, na.rm = TRUE), 2)

cd_fp_epsi_base_post <- round((mean_fp_epsi_post - mean_fp_epsi_base) / sqrt((sd_fp_epsi_base^2 + sd_fp_epsi_post^2) / 2), 2)
cd_fp_epsi_base_wk8 <- round((mean_fp_epsi_wk8 - mean_fp_epsi_base) / sqrt((sd_fp_epsi_base^2 + sd_fp_epsi_wk8^2) / 2), 2)

###BP EPSI subscale analysis###
mean_bp_epsi_base <- round(mean(bp_baseline$epsi_neg_obese_25, na.rm = TRUE), 2)
mean_bp_epsi_post <- round(mean(bp_post$epsi_neg_obese_25, na.rm = TRUE), 2)
mean_bp_epsi_wk8 <- round(mean(bp_8wk$epsi_neg_obese_25, na.rm = TRUE), 2)

sd_bp_epsi_base <- round(sd(bp_baseline$epsi_neg_obese_25, na.rm = TRUE), 2)
sd_bp_epsi_post <- round(sd(bp_post$epsi_neg_obese_25, na.rm = TRUE), 2)
sd_bp_epsi_wk8 <- round(sd(bp_8wk$epsi_neg_obese_25, na.rm = TRUE), 2)

cd_bp_epsi_base_post <- round((mean_bp_epsi_post - mean_bp_epsi_base) / sqrt((sd_bp_epsi_base^2 + sd_bp_epsi_post^2) / 2), 2)

cd_bp_epsi_base_wk8 <- round((mean_bp_epsi_wk8 - mean_bp_epsi_base) / sqrt((sd_bp_epsi_base^2 + sd_bp_epsi_wk8^2) / 2), 2)
```

```{r message=FALSE, echo=FALSE, warning=FALSE}
###BAM SATAQ Analysis###
mean_fp_sataq_base <- round(mean(bam_baseline$sataq_average_25, na.rm = TRUE), 2)
mean_fp_sataq_post <- round(mean(bam_post$sataq_average_25, na.rm = TRUE), 2)
mean_fp_sataq_wk8 <- round(mean(bam_8week$sataq_average_25, na.rm = TRUE), 2)

sd_fp_sataq_base <- round(sd(bam_baseline$sataq_average_25, na.rm = TRUE), 2)
sd_fp_sataq_post <- round(sd(bam_post$sataq_average_25, na.rm = TRUE), 2)
sd_fp_sataq_wk8 <- round(sd(bam_8week$sataq_average_25, na.rm = TRUE), 2)

cd_fp_sataq_base_post <- round((mean_fp_sataq_post - mean_fp_sataq_base) / sqrt((sd_fp_sataq_base^2 + sd_fp_sataq_post^2) / 2), 2)
cd_fp_sataq_base_wk8 <- round((mean_fp_sataq_wk8 - mean_fp_sataq_base) / sqrt((sd_fp_sataq_base^2 + sd_fp_sataq_wk8^2) / 2), 2)
cd_fp_sataq_post_wk8 <- round((mean_fp_sataq_wk8 - mean_fp_sataq_post) / sqrt((sd_fp_sataq_post^2 + sd_fp_sataq_wk8^2) / 2), 2)

###BP SATAQ Analysis###
mean_bp_sataq_base <- round(mean(bp_baseline$sataq_average_25, na.rm = TRUE), 2)
mean_bp_sataq_post <- round(mean(bp_post$sataq_average_25, na.rm = TRUE), 2)
mean_bp_sataq_wk8 <- round(mean(bp_8wk$sataq_average_25, na.rm = TRUE), 2)

sd_bp_sataq_base <- round(sd(bp_baseline$sataq_average_25, na.rm = TRUE), 2)
sd_bp_sataq_post <- round(sd(bp_post$sataq_average_25, na.rm = TRUE), 2)
sd_bp_sataq_wk8 <- round(sd(bp_8wk$sataq_average_25, na.rm = TRUE), 2)

cd_bp_sataq_base_post <- round((mean_bp_sataq_post - mean_bp_sataq_base) / sqrt((sd_bp_sataq_base^2 + sd_bp_sataq_post^2) / 2), 2)
cd_bp_sataq_base_wk8 <- round((mean_bp_sataq_wk8 - mean_bp_sataq_base) / sqrt((sd_bp_sataq_base^2 + sd_bp_sataq_wk8^2) / 2), 2)
cd_bp_sataq_post_wk8 <- round((mean_bp_sataq_wk8 - mean_bp_sataq_post) / sqrt((sd_bp_sataq_post^2 + sd_bp_sataq_wk8^2) / 2), 2)
```

```{r message=FALSE, echo=FALSE, warning=FALSE}
###BAM IBSS-R Analysis###
mean_fp_ibssr_base <- round(mean(bam_baseline$ibssr_mean_25, na.rm = TRUE), 2)
mean_fp_ibssr_post <- round(mean(bam_post$ibssr_mean_25, na.rm = TRUE), 2)
mean_fp_ibssr_wk8 <- round(mean(bam_8week$ibssr_mean_25, na.rm = TRUE), 2)

sd_fp_ibssr_base <- round(sd(bam_baseline$ibssr_mean_25, na.rm = TRUE), 2)
sd_fp_ibssr_post <- round(sd(bam_post$ibssr_mean_25, na.rm = TRUE), 2)
sd_fp_ibssr_wk8 <- round(sd(bam_8week$ibssr_mean_25, na.rm = TRUE), 2)

cd_fp_ibssr_base_post <- round((mean_fp_ibssr_post - mean_fp_ibssr_base) / sqrt((sd_fp_ibssr_base^2 + sd_fp_ibssr_post^2) / 2), 2)
cd_fp_ibssr_base_wk8 <- round((mean_fp_ibssr_wk8 - mean_fp_ibssr_base) / sqrt((sd_fp_ibssr_base^2 + sd_fp_ibssr_wk8^2) / 2), 2)
cd_fp_ibssr_post_wk8 <- round((mean_fp_ibssr_wk8 - mean_fp_ibssr_post) / sqrt((sd_fp_ibssr_post^2 + sd_fp_ibssr_wk8^2) / 2), 2)

###BP IBSSR Analysis###
mean_bp_ibssr_base <- round(mean(bp_baseline$ibssr_mean_25, na.rm = TRUE), 2)
mean_bp_ibssr_post <-round( mean(bp_post$ibssr_mean_25, na.rm = TRUE), 2)
mean_bp_ibssr_wk8 <- round(mean(bp_8wk$ibssr_mean_25, na.rm = TRUE), 2)

sd_bp_ibssr_base <- round(sd(bp_baseline$ibssr_mean_25, na.rm = TRUE), 2)
sd_bp_ibssr_post <- round(sd(bp_post$ibssr_mean_25, na.rm = TRUE), 2)
sd_bp_ibssr_wk8 <- round(sd(bp_8wk$ibssr_mean_25, na.rm = TRUE), 2)

cd_bp_ibssr_base_post <- round((mean_bp_ibssr_post - mean_bp_ibssr_base) / sqrt((sd_bp_ibssr_base^2 + sd_bp_ibssr_post^2) / 2), 2)
cd_bp_ibssr_base_wk8 <- round((mean_bp_ibssr_wk8 - mean_bp_ibssr_base) / sqrt((sd_bp_ibssr_base^2 + sd_bp_ibssr_wk8^2) / 2), 2)
cd_bp_ibssr_post_wk8 <- round((mean_bp_ibssr_wk8 - mean_bp_ibssr_post) / sqrt((sd_bp_ibssr_post^2 + sd_bp_ibssr_wk8^2) / 2), 2)
```

Baseline Levels

```{r}
mean_base_gffs <- mean(total_baseline_data$gffs_sum_25, na.rm = TRUE)
range_base_gffs <- range(total_baseline_data$gffs_sum_25, na.rm = TRUE)
sd_base_gffs <- sd(total_baseline_data$gffs_sum_25, na.rm = TRUE)
```

```{r}
mean_epsi_bd <- mean(total_baseline_data$epsi_body_dissatisfaction_25, na.rm = TRUE)
range_base_epsi_bd <- range(total_baseline_data$epsi_body_dissatisfaction_25, na.rm = TRUE)
sd_base_epsi_bd <- sd(total_baseline_data$epsi_body_dissatisfaction_25, na.rm = TRUE)
```

```{r}
total_baseline_data <- subset(BAM_redcap_long_merged,timepoint == 'baseline')

variables <- c("epsi_body_dissatisfaction_25","epsi_binge_25", "epsi_restraint_25", "epsi_purging_25",
               "epsi_restrict_25", "epsi_exercise_25", "epsi_neg_obese_25",
               "epsi_muscle_build_25")

# Initialize empty lists to store results
epsi_means <- vector("numeric", length(variables))
epsi_ranges <- vector("list", length(variables))
epsi_sds <- vector("numeric", length(variables))

# Loop through each variable
for (i in seq_along(variables)) {
  variable <- variables[i]
  
  # Calculate mean
  epsi_means[i] <- mean(total_baseline_data[[variable]], na.rm = TRUE)
  
  # Calculate range
  epsi_ranges[i] <- range(total_baseline_data[[variable]], na.rm = TRUE)
  
  # Calculate standard deviation
  epsi_sds[i] <- sd(total_baseline_data[[variable]], na.rm = TRUE)
}

# Create a data frame with the results
epsi_sd_list <- list(epsi_sds)
sd_epsi <- do.call(rbind, epsi_sds)

save(sd_epsi, file = 'tabs/results_tables.RData')

sd_epsi$SD <- round(sd_epsi$SD, 2)
```
