# References {.unnumbered}

::: {#refs}
**References**

Becker, C. B., Smith, L. M., & Ciao, A. C. (2006). Peer-facilitated eating disorder prevention: A randomized effectiveness trial of cognitive dissonance and media advocacy. Journal of
Counseling Psychology, 53(4), 550.

Becker, C. B., & Stice, E. (2017). From efficacy to effectiveness to broad implementation:
Evolution of the Body Project. Journal of Consulting and Clinical Psychology, 85(8),
767--782. https://doi.org/10.1037/ccp0000204

Borgers, T., Krüger, N., Vocks, S., Thomas, J. J., Plessow, F., & Hartmann, A. S. (2021).
Overcoming limitations of self-report: An assessment of fear of weight gain in anorexia
nervosa and healthy controls using implicit association tests. Journal of Eating
Disorders, 9(1), 26. https://doi.org/10.1186/s40337-021-00379-8

Brownell, K. D. (2005). Introduction: The social, scientific, and human context of prejudice and discrimination based on weight. Weight Bias: Nature, Consequences, and Remedies, 1--
11.

Coniglio, K. A., Becker, K. R., Tabri, N., Keshishian, A. C., Miller, J. D., Eddy, K. T., &
Thomas, J. J. (2018). Factorial integrity and validation of the Eating Pathology
Symptoms Inventory (EPSI). Eating Behaviors, 31, 1--7.
https://doi.org/10.1016/j.eatbeh.2018.07.004

Durso, L. E., & Latner, J. D. (2008). Understanding self-directed stigma: Development of the weight bias internalization scale. Obesity (Silver Spring, Md.), 16 Suppl 2, S80-86.
https://doi.org/10.1038/oby.2008.448

Durso, L. E., Latner, J. D., White, M. A., Masheb, R. M., Blomquist, K. K., Morgan, P. T., &
Grilo, C. M. (2012). Internalized weight bias in obese patients with binge eating disorder:
Associations with eating disturbances and psychological functioning. International
Journal of Eating Disorders, 45(3), 423--427. https://doi.org/10.1002/eat.20933

Forbush, K. T., Wildes, J. E., Pollack, L. O., Dunbar, D., Luo, J., Patterson, K., Petruzzi, L.,
Pollpeter, M., Miller, H., Stone, A., Bright, A., & Watson, D. (2013). Development and
validation of the Eating Pathology Symptoms Inventory (EPSI). Psychological
Assessment, 25(3), 859--878. https://doi.org/10.1037/a0032639

Forney, K. J., Schwendler, T., & Ward, R. M. (2019). Examining similarities in eating
pathology, negative affect, and perfectionism among peers: A social network analysis.
Appetite, 137, 236--243. https://doi.org/10.1016/j.appet.2019.03.013

Ghaderi, A., Stice, E., Andersson, G., Enö Persson, J., & Allzén, E. (2020). A randomized
controlled trial of the effectiveness of virtually delivered Body Project (vBP) groups to
prevent eating disorders. Journal of Consulting and Clinical Psychology, 88(7), 643--656.
https://doi.org/10.1037/ccp0000506

Goldfarb, L. A., Dykens, E. M., & Gerrard, M. (1985). The Goldfarb Fear of Fat Scale. Journal
of Personality Assessment, 49(3), 329--332.
https://doi.org/10.1207/s15327752jpa4903_21

Laboe, A. A., Shah, J., & Fitzsimmons-Craft, E. E. (2023). The Transition to College as a Risk Factor for Eating Disorders. In P. Robinson, T. Wade, B. Herpertz-Dahlmann, F.
Fernandez-Aranda, J. Treasure, & S. Wonderlich (Eds.), Eating Disorders: An
International Comprehensive View (pp. 1--17). Springer International Publishing.
https://doi.org/10.1007/978-3-030-97416-9_27-1

Latner, J. D., O\'Brien, K. S., Durso, L. E., Brinkman, L. A., & MacDonald, T. (2008). Weighing
obesity stigma: The relative strength of different forms of bias. International Journal of
Obesity, 32(7), Article 7. https://doi.org/10.1038/ijo.2008.53

Levinson, C. A., Rapp, J., & Riley, E. N. (2014). Addressing the fear of fat: Extending imaginal
exposure therapy for anxiety disorders to anorexia nervosa. Eat Weight Disord, 19(4),
521--524.

Levinson, C. A., Vanzhula, I. A., & Christian, C. (2019). Development and validation of the
eating disorder fear questionnaire and interview: Preliminary investigation of eating
disorder fears. Eating Behaviors, 35, 101320.
https://doi.org/10.1016/j.eatbeh.2019.101320
				

Levinson, C. A., & Williams, B. M. (2020). Eating disorder fear networks: Identification of
central eating disorder fears. International Journal of Eating Disorders, 53(12), 1960--
1973. https://doi.org/10.1002/eat.23382
				

Levinson, C. A., Zerwas, S., Calebs, B., Forbush, K., Kordy, H., Watson, H., Hofmeier, S.,
Levine, M., Crosby, R. D., Peat, C., Runfola, C. D., Zimmer, B., Moesner, M., Marcus,
M. D., & Bulik, C. M. (2017). The core symptoms of bulimia nervosa, anxiety, and
depression: A network analysis. Journal of Abnormal Psychology, 126(3), 340--354.
https://doi.org/10.1037/abn0000254
				

Mehak, A., Friedman, A., & Cassin, S. E. (2018). Self-objectification, weight bias
internalization, and binge eating in young women: Testing a mediational model. Body
Image, 24, 111--115. https://doi.org/10.1016/j.bodyim.2018.01.002				

O\'Brien, K. S., Latner, J. D., Puhl, R. M., Vartanian, L. R., Giles, C., Griva, K., & Carter, A.
(2016). The relationship between weight stigma and eating behavior is explained by weight bias internalization and psychological distress. Appetite, 102, 70--76.
https://doi.org/10.1016/j.appet.2016.02.032\

Przybyta-Basista, H., Buszman, K., & Flakus, M. (2022). An examination of the factor structure of the Goldfarb Fear of Fat Scale in clinical and non-clinical samples of Polish women. Body Image, 40, 58--66. https://doi.org/10.1016/j.bodyim.2021.11.003\

Romano, K. A., Heron, K. E., & Henson, J. M. (2021). Examining associations among weight
stigma, weight bias internalization, body dissatisfaction, and eating disorder symptoms:
Does weight status matter? Body Image, 37, 38--49.
https://doi.org/10.1016/j.bodyim.2021.01.006

Schaefer, L. M., Burke, N. L., Thompson, J. K., Dedrick, R. F., Heinberg, L. J., Calogero, R. M., Bardone-Cone, A. M., Higgins, M. K., Frederick, D. A., Kelly, M., Anderson, D. A.,
Schaumberg, K., Nerini, A., Stefanile, C., Dittmar, H., Clark, E., Adams, Z., Macwana,
S., Klump, K. L., \... Swami, V. (2015). Development and validation of the Sociocultural
Attitudes Towards Appearance Questionnaire-4 (SATAQ-4). Psychological Assessment,
27(1), 54--67. https://doi.org/10.1037/a0037917

Stice, E., Marti, C. N., Shaw, H., & Rohde, P. (2019). Meta-analytic review of dissonance-based
eating disorder prevention programs: Intervention, participant, and facilitator features that
predict larger effects. Clinical Psychology Review, 70, 91--107.
https://doi.org/10.1016/j.cpr.2019.04.004

Stice, E., Nemeroff, C., & Shaw, H. (1996). Test of the dual pathway model of bulimia nervosa: Evidence for dietary restraint and affect regulation mechanisms. Journal of Social & Clinical Psychology, 15(3), 340--363.

Stice, E., Onipede, Z. A., & Marti, C. N. (2021). A meta-analytic review of trials that tested
whether eating disorder prevention programs prevent eating disorder onset. Clinical
Psychology Review, 87, 102046. https://doi.org/10.1016/j.cpr.2021.102046

Stice, E., Rohde, P., & Shaw, H. (2012). The Body Project: A Dissonance-Based Eating
Disorder Prevention Intervention. Oxford University Press.
					

Sullivan, G. M., & Feinn, R. (2012). Using Effect Size---Or Why the P Value Is Not Enough.
Journal of Graduate Medical Education, 4(3), 279--282. https://doi.org/10.4300/JGME-
D-12-00156.1

The Body Project. (2020, March 9). National Eating Disorders Association.
https://www.nationaleatingdisorders.org/get-involved/the-body-project

Vanderkruik, R., Gist, D., & Dimidjian, S. (2020). Preventing eating disorders in young women: An RCT and mixed-methods evaluation of the peer-delivered Body Project. Journal of Consulting and Clinical Psychology, 88(12), 1105--1118. https://doi.org/10.1037/ccp0000609.supp
					

Wang, S. B., Jones, P. J., Dreier, M., Elliott, H., & Grilo, C. M. (2019). Core psychopathology of treatment-seeking patients with binge-eating disorder: A network analysis investigation. Psychological Medicine, 49(11), 1923--1928.
https://doi.org/10.1017/S0033291718002702
:::
